//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecycleItemsView.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecycleItemsView.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Effect - Additional Details.
        /// </summary>
        public static string AdditionalDetails {
            get {
                return ResourceManager.GetString("AdditionalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Effect - Additional Info.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecycleItemsView.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecycleItemsView.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Effect - Changing Background Color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Effect - Bold Text.
        /// </summary>
        public static string BoldText {
            get {
                return ResourceManager.GetString("BoldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Effect - Border.
        /// </summary>
        public static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROWSE MORE.
        /// </summary>
        public static string BrowseMore {
            get {
                return ResourceManager.GetString("BrowseMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Effect - Details on Image.
        /// </summary>
        public static string DetailsOnImage {
            get {
                return ResourceManager.GetString("DetailsOnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageCell.
        /// </summary>
        public static string ImageCell {
            get {
                return ResourceManager.GetString("ImageCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Effect - Expand Image.
        /// </summary>
        public static string ImageExpansion {
            get {
                return ResourceManager.GetString("ImageExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Effect - Expand Image and Info.
        /// </summary>
        public static string ImageInfoExpansion {
            get {
                return ResourceManager.GetString("ImageInfoExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Effect - Changing Info Color.
        /// </summary>
        public static string InfoColor {
            get {
                return ResourceManager.GetString("InfoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info On The Right.
        /// </summary>
        public static string InfoOnTheRight {
            get {
                return ResourceManager.GetString("InfoOnTheRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Line Title.
        /// </summary>
        public static string OneLineTitle {
            get {
                return ResourceManager.GetString("OneLineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounded Corner.
        /// </summary>
        public static string RoundedCorner {
            get {
                return ResourceManager.GetString("RoundedCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TizenItemName.
        /// </summary>
        public static string TizenItemNamePageTitle {
            get {
                return ResourceManager.GetString("TizenItemNamePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Line Title.
        /// </summary>
        public static string TwoLineTitle {
            get {
                return ResourceManager.GetString("TwoLineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Line Title + Info.
        /// </summary>
        public static string TwoLineTitleInfo {
            get {
                return ResourceManager.GetString("TwoLineTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string WithHeader {
            get {
                return ResourceManager.GetString("WithHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info with Icon.
        /// </summary>
        public static string WithIcon {
            get {
                return ResourceManager.GetString("WithIcon", resourceCulture);
            }
        }
    }
}
